# Generated by Django 5.2.6 on 2025-10-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
